package com.mlmishra.bhupendramishra.allelectronics;

import android.app.AlertDialog;
import android.content.Context;
import android.content.DialogInterface;
import android.content.Intent;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.text.InputType;
import android.view.Menu;
import android.view.MenuItem;
import android.view.View;
import android.view.inputmethod.InputMethodManager;
import android.widget.EditText;
import android.widget.TextView;
import android.graphics.Color;
import android.widget.Button;
import android.view.View.OnClickListener;
import android.widget.Toast;
import android.widget.CheckBox;
import android.widget.RadioButton;
import android.widget.RadioGroup;
import android.app.Activity;


public class Controller_program extends Activity {
    String separator = System.getProperty("line.separator");
    TextView textview19;
    String lcd_connections=separator+"PORT BIT 0 ----> LCD PIN 4"+separator+"PORT BIT 1 ----> LCD PIN 5"+separator+"PORT BIT 2 ----> LCD PIN 6"+separator+"PORT BIT 3 ----> FREE"+separator+"PORT BIT 4 ----> LCD PIN 11"+separator+"PORT BIT 5 ----> LCD PIN 12"+separator+"PORT BIT 6 ----> LCD PIN 13"+separator+"PORT BIT 7 ----> LCD PIN 14";
    private Button button;
    private String filename,write_data;
    private EditText timer0value;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        //getSupportActionBar().hide();
        setContentView(R.layout.activity_controller_program);
        textview19 = (TextView) findViewById(R.id.textView19);
        textview19.setTextColor(Color.BLUE);
        textview19.setText(lcd_connections);
        timer0value=(EditText)findViewById(R.id.t1et1);
        button=(Button)findViewById(R.id.button3);
        button.setOnClickListener(new OnClickListener() {

            @Override
            public void onClick(View arg0) {

                AlertDialog.Builder builder = new AlertDialog.Builder(Controller_program.this);
                builder.setTitle("Enter Filename");

                final EditText input = new EditText(Controller_program.this);

                input.setInputType(InputType.TYPE_CLASS_TEXT);
                builder.setView(input);


                builder.setPositiveButton("OK", new DialogInterface.OnClickListener() {
                    @Override
                    public void onClick(DialogInterface dialog, int which) {
                        filename = input.getText().toString();
                        write_data = "/*C Program Generated by Allelectronics" + separator + "Project :" + separator + "Version :Can be Compiled with Codevision AVR v 3.22 compiler" + separator + "Date :" + separator + "Author :" + separator + "Comments :" + separator + separator + "Chip Type : ATMEGA8L running on 1MHz (internal oscillator)" + separator + "*/" + separator + separator + include_file() + lcd_port_congig() + ADC_config() + interuppt_init() + timer0_interrupt() + timer1_interrupt() + timer2_interrupt() + timer2_compare_interrupt() + "void main()" + separator + "{" + separator + separator + "//PORT B CONFIGURATION" + separator + separator + "DDRB=" + PortB_ddrb() + ";" + separator + "PORTB=" + PortB() + ";" + separator + separator + "//PORT C CONFIGURATION" + separator + separator + "DDRC=" + PortC_ddrb() + ";" + separator + "PORTC=" + PortC() + ";" + separator + separator + "//PORT D CONFIGURATION" + separator + separator + "DDRD=" + PortD_ddrb() + ";" + separator + "PORTD=" + PortD() + ";" + separator + separator + adc_clock() + separator + separator + lcd_init() + separator + separator + interuppt_prog() + separator + separator + usart_init() + separator + separator + timer0_init() + separator + timer1_prog() + separator + timer2_prog() + separator +timer_int_init()+separator+ any_interrupt() + separator + separator + end();
                        Global.write_file1(filename, write_data, Controller_program.this);
                        InputMethodManager mgr = (InputMethodManager) getSystemService(Context.INPUT_METHOD_SERVICE);
                        mgr.hideSoftInputFromWindow(input.getWindowToken(), 0);
                        Toast.makeText(Controller_program.this, "C file Generated and saved in your library, same can be found in storge media also", Toast.LENGTH_LONG).show();

                    }
                });
                builder.setNegativeButton("Cancel", new DialogInterface.OnClickListener() {
                    @Override
                    public void onClick(DialogInterface dialog, int which) {
                        dialog.cancel();
                        InputMethodManager mgr = (InputMethodManager) getSystemService(Context.INPUT_METHOD_SERVICE);
                        mgr.hideSoftInputFromWindow(input.getWindowToken(), 0);
                    }
                });

                builder.show();
            }

        });

    }
    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        // Inflate the menu_ladder; this adds items to the action bar if it is present.
        getMenuInflater().inflate(R.menu.menu_controller_program, menu);
        return true;
    }

    @Override
    public void onBackPressed() {

            Intent intent = new Intent(Controller_program.this, Table_content.class);
            startActivity(intent);
            finish();
        }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        // Handle action bar item clicks here. The action bar will
        // automatically handle clicks on the Home/Up button, so long
        // as you specify a parent activity in AndroidManifest.xml.
        int id = item.getItemId();

        //noinspection SimplifiableIfStatement
        if (id == R.id.action_settings) {
            return true;
        }

        return super.onOptionsItemSelected(item);
    }

    private String PortB_ddrb()
    {
        String data;
        data="0b";
        boolean isChecked=false,isda,ist1a,ist1b;
        isda = ((RadioButton) findViewById(R.id.t021)).isChecked();
        ist1a = ((RadioButton) findViewById(R.id.ta11)).isChecked();
        ist1b = ((RadioButton) findViewById(R.id.tb11)).isChecked();
        int i;
        for(i=15;i>=1;i=i-2) {

            if(i==1) {
                isChecked = ((CheckBox) findViewById(R.id.checkBox)).isChecked();
            }
            else if(i==3)
            {
                isChecked = ((CheckBox) findViewById(R.id.checkBox3)).isChecked();
            }
            else if(i==5)
            {
                isChecked = ((CheckBox) findViewById(R.id.checkBox5)).isChecked() |  !ist1a ;
            }
            else if(i==7)
            {
                isChecked = ((CheckBox) findViewById(R.id.checkBox7)).isChecked() | !isda | !ist1b ;
            }
            else if(i==9)
            {
                isChecked = ((CheckBox) findViewById(R.id.checkBox9)).isChecked();
            }
            else if(i==11)
            {
                isChecked = ((CheckBox) findViewById(R.id.checkBox11)).isChecked();
            }

            else if(i==13)
            {
                isChecked = ((CheckBox) findViewById(R.id.checkBox13)).isChecked();
            }

            else if(i==15)
            {
                isChecked = ((CheckBox) findViewById(R.id.checkBox15)).isChecked();
            }


            if (isChecked) {
                data=data+"1";

            } else {
                data=data+"0";
            }
        }
                return data;
    }

    private String PortB()
    {
        String data;
        data="0b";
        boolean isChecked=false;
        int i;
        for(i=15;i>=1;i=i-2) {

            if(i==1) {
                isChecked = ((CheckBox) findViewById(R.id.checkBox2)).isChecked();
            }
            else if(i==3)
            {
                isChecked = ((CheckBox) findViewById(R.id.checkBox4)).isChecked();
            }
            else if(i==5)
            {
                isChecked = ((CheckBox) findViewById(R.id.checkBox6)).isChecked();
            }
            else if(i==7)
            {
                isChecked = ((CheckBox) findViewById(R.id.checkBox8)).isChecked();
            }
            else if(i==9)
            {
                isChecked = ((CheckBox) findViewById(R.id.checkBox10)).isChecked();
            }
            else if(i==11)
            {
                isChecked = ((CheckBox) findViewById(R.id.checkBox12)).isChecked();
            }

            else if(i==13)
            {
                isChecked = ((CheckBox) findViewById(R.id.checkBox14)).isChecked();
            }

            else if(i==15)
            {
                isChecked = ((CheckBox) findViewById(R.id.checkBox16)).isChecked();
            }


            if (isChecked) {
                data=data+"1";

            } else {
                data=data+"0";
            }
        }
        return data;
    }


    private String PortC_ddrb()
    {
        String data;
        data="0b";
        boolean isChecked=false;
        int i;
        for(i=15;i>=1;i=i-2) {

            if(i==1) {
                isChecked = ((CheckBox) findViewById(R.id.checkBox17)).isChecked();
            }
            else if(i==3)
            {
                isChecked = ((CheckBox) findViewById(R.id.checkBox19)).isChecked();
            }
            else if(i==5)
            {
                isChecked = ((CheckBox) findViewById(R.id.checkBox21)).isChecked();
            }
            else if(i==7)
            {
                isChecked = ((CheckBox) findViewById(R.id.checkBox23)).isChecked();
            }
            else if(i==9)
            {
                isChecked = ((CheckBox) findViewById(R.id.checkBox25)).isChecked();
            }
            else if(i==11)
            {
                isChecked = ((CheckBox) findViewById(R.id.checkBox27)).isChecked();
            }

            else if(i==13)
            {
                isChecked = ((CheckBox) findViewById(R.id.checkBox29)).isChecked();
            }

            else if(i==15)
            {
                isChecked = ((CheckBox) findViewById(R.id.checkBox31)).isChecked();
            }


            if (isChecked) {
                data=data+"1";

            } else {
                data=data+"0";
            }
        }
        return data;
    }

    private String PortC()
    {
        String data;
        data="0b";
        boolean isChecked=false;
        int i;
        for(i=15;i>=1;i=i-2) {

            if(i==1) {
                isChecked = ((CheckBox) findViewById(R.id.checkBox18)).isChecked();
            }
            else if(i==3)
            {
                isChecked = ((CheckBox) findViewById(R.id.checkBox20)).isChecked();
            }
            else if(i==5)
            {
                isChecked = ((CheckBox) findViewById(R.id.checkBox22)).isChecked();
            }
            else if(i==7)
            {
                isChecked = ((CheckBox) findViewById(R.id.checkBox24)).isChecked();
            }
            else if(i==9)
            {
                isChecked = ((CheckBox) findViewById(R.id.checkBox26)).isChecked();
            }
            else if(i==11)
            {
                isChecked = ((CheckBox) findViewById(R.id.checkBox28)).isChecked();
            }

            else if(i==13)
            {
                isChecked = ((CheckBox) findViewById(R.id.checkBox30)).isChecked();
            }

            else if(i==15)
            {
                isChecked = ((CheckBox) findViewById(R.id.checkBox32)).isChecked();
            }


            if (isChecked) {
                data=data+"1";

            } else {
                data=data+"0";
            }
        }
        return data;
    }
    private String PortD_ddrb()
    {
        String data;
        data="0b";
        boolean isChecked=false;
        int i;
        for(i=15;i>=1;i=i-2) {

            if(i==1) {
                isChecked = ((CheckBox) findViewById(R.id.checkBox33)).isChecked();
            }
            else if(i==3)
            {
                isChecked = ((CheckBox) findViewById(R.id.checkBox35)).isChecked();
            }
            else if(i==5)
            {
                isChecked = ((CheckBox) findViewById(R.id.checkBox37)).isChecked();
            }
            else if(i==7)
            {
                isChecked = ((CheckBox) findViewById(R.id.checkBox39)).isChecked();
            }
            else if(i==9)
            {
                isChecked = ((CheckBox) findViewById(R.id.checkBox41)).isChecked();
            }
            else if(i==11)
            {
                isChecked = ((CheckBox) findViewById(R.id.checkBox43)).isChecked();
            }

            else if(i==13)
            {
                isChecked = ((CheckBox) findViewById(R.id.checkBox45)).isChecked();
            }

            else if(i==15)
            {
                isChecked = ((CheckBox) findViewById(R.id.checkBox47)).isChecked();
            }


            if (isChecked) {
                data=data+"1";

            } else {
                data=data+"0";
            }
        }
        return data;
    }

    private String PortD()
    {
        String data;
        data="0b";
        boolean isChecked=false;
        int i;
        for(i=15;i>=1;i=i-2) {

            if(i==1) {
                isChecked = ((CheckBox) findViewById(R.id.checkBox34)).isChecked();
            }
            else if(i==3)
            {
                isChecked = ((CheckBox) findViewById(R.id.checkBox36)).isChecked();
            }
            else if(i==5)
            {
                isChecked = ((CheckBox) findViewById(R.id.checkBox38)).isChecked();
            }
            else if(i==7)
            {
                isChecked = ((CheckBox) findViewById(R.id.checkBox40)).isChecked();
            }
            else if(i==9)
            {
                isChecked = ((CheckBox) findViewById(R.id.checkBox43)).isChecked();
            }
            else if(i==11)
            {
                isChecked = ((CheckBox) findViewById(R.id.checkBox44)).isChecked();
            }

            else if(i==13)
            {
                isChecked = ((CheckBox) findViewById(R.id.checkBox46)).isChecked();
            }

            else if(i==15)
            {
                isChecked = ((CheckBox) findViewById(R.id.checkBox48)).isChecked();
            }


            if (isChecked) {
                data=data+"1";

            } else {
                data=data+"0";
            }
        }
        return data;
    }

    private String ADC_config()
    {
        boolean isChecked1=false;
        boolean isAvcc,isAref,is8bit,isintcap;
        String data="",data1="";
        isAvcc = ((RadioButton) findViewById(R.id.ADC2)).isChecked();
        isAref = ((RadioButton) findViewById(R.id.ADC1)).isChecked();
        is8bit = ((CheckBox) findViewById(R.id.checkBox52)).isChecked();
        isintcap = ((RadioButton) findViewById(R.id.ADC3)).isChecked();

        isChecked1 = ((CheckBox) findViewById(R.id.checkBox51)).isChecked();

        if(isChecked1)
        {
            data=data+separator+"#define ADC_VREF_TYPE (";
            if(isAvcc)
            {
              data=data+"(0<<REFS1) | (1<<REFS0)";
            }
            else if(isAref)
            {
                data=data+"(0<<REFS1) | (0<<REFS0)";
            }
            else if(isintcap)
            {
                data=data+"(1<<REFS1) | (0<<REFS0)";
            }
            if(is8bit)
            {
                data=data+" | (1<<ADLAR))";
                data1="return ADCH;";
            }
            else
            {
                data=data+" | (0<<ADLAR))";
                data1="return ADCW;";
            }
            data=data+separator+separator+"//Read the AD Conversion Result"+separator+separator+"unsigned int read_adc(unsigned char adc_input)"+separator+"{"+separator+"ADMUX=adc_input | ADC_VREF_TYPE;"+separator+"delay_us(10);"+separator+"//start the AD Conversion"+separator+"ADCSRA |=(1<<ADSC);"+separator+"//wait for the AD conversion to complete"+separator+"while((ADCSRA & (1<<ADIF))==0);"+separator+"ADCSRA|=(1<<ADIF);"+separator+data1+separator+"}"+separator+separator;

        }
        return data;

    }

    private String adc_clock()
    {
        String data="//ADC Initialization"+separator+separator;
        boolean is250,is125,is625,isadce;
        is250 = ((RadioButton) findViewById(R.id.ADC4)).isChecked();
        is125 = ((RadioButton) findViewById(R.id.ADC5)).isChecked();
        isadce = ((CheckBox) findViewById(R.id.checkBox51)).isChecked();
        is625 = ((RadioButton) findViewById(R.id.ADC6)).isChecked();
        if(isadce)
        {
            if(is250)
            {
                data=data+"//ADC Clock Frequency : 250KHz"+separator+"ADMUX=ADC_VREF_TYPE;"+separator+"ADCSRA=(1<<ADEN) | (0<<ADSC) | (0<<ADFR) | (0<<ADIF) | (0<<ADIE) | (0<<ADPS2) | (1<<ADPS1) | (0<<ADPS0);"+separator+"SFIOR=(0<<ACME);";
            }
            else if(is125)
            {
                data=data+"//ADC Clock Frequency : 125KHz"+separator+"ADMUX=ADC_VREF_TYPE;"+separator+"ADCSRA=(1<<ADEN) | (0<<ADSC) | (0<<ADFR) | (0<<ADIF) | (0<<ADIE) | (0<<ADPS2) | (1<<ADPS1) | (1<<ADPS0);"+separator+"SFIOR=(0<<ACME);";
            }
            else if(is625)
            {
                data=data+"//ADC Clock Frequency : 62.5KHz"+separator+"ADMUX=ADC_VREF_TYPE;"+separator+"ADCSRA=(1<<ADEN) | (0<<ADSC) | (0<<ADFR) | (0<<ADIF) | (0<<ADIE) | (1<<ADPS2) | (0<<ADPS1) | (0<<ADPS0);"+separator+"SFIOR=(0<<ACME);";
            }
        }
        else
        {
            data=data+"//ADC Clock Frequency : ADC DISABLED"+separator+"ADCSRA=(0<<ADEN) | (0<<ADSC) | (0<<ADFR) | (0<<ADIF) | (0<<ADIE) | (0<<ADPS2) | (0<<ADPS1) | (0<<ADPS0);"+separator+"SFIOR=(0<<ACME);";
        }

        return data;
    }

    private String include_file()
    {
        String data="#include<mega8.h>"+separator;
        boolean islcden,isadcen,isusarttx,isusartrx;
        islcden = ((CheckBox) findViewById(R.id.checkBox100)).isChecked();
        isadcen = ((CheckBox) findViewById(R.id.checkBox51)).isChecked();
        isusarttx = ((CheckBox) findViewById(R.id.checkBox53)).isChecked();
        isusartrx = ((CheckBox) findViewById(R.id.checkBox54)).isChecked();

        if(islcden)
        {
            data=data+"#include<lcd.h>"+separator;
        }

        if(isadcen)
        {
            data=data+"#include<delay.h>"+separator;
        }

        if(isusartrx | isusarttx)
        {
            data=data+"#include<stdio.h>"+separator;
        }

        return data;

    }

    private String lcd_port_congig()
    {
        String data="";
        boolean islcden,islcdpb,islcdpd;

        islcden = ((CheckBox) findViewById(R.id.checkBox100)).isChecked();
        islcdpb = ((RadioButton) findViewById(R.id.L1)).isChecked();
        islcdpd = ((RadioButton) findViewById(R.id.L2)).isChecked();
        if(islcden)
        {
            if(islcdpb)
            {
                data=separator+data+"#asm"+separator+".equ __lcd_port=0x18"+separator+"#endasm"+separator;
            }
            else if(islcdpd)
            {
                data=separator+data+"#asm"+separator+".equ __lcd_port=0x12"+separator+"#endasm"+separator;
            }
        }
        return data;
    }

    private String lcd_init()
    {
        String data="";
        boolean islcden,islc1,islc2,islc3,islc4;

        islcden = ((CheckBox) findViewById(R.id.checkBox100)).isChecked();
        islc1 = ((RadioButton) findViewById(R.id.Lc1)).isChecked();
        islc2 = ((RadioButton) findViewById(R.id.Lc2)).isChecked();
        islc3 = ((RadioButton) findViewById(R.id.Lc3)).isChecked();
        islc4 = ((RadioButton) findViewById(R.id.Lc4)).isChecked();
        if(islcden)
        {
            data=data+"//LCD Initialization"+separator;
            if(islc1)
            {
                data=data+"lcd_init("+"8"+");"+separator;
            }
            else if(islc2)
            {
                data=data+"lcd_init("+"16"+");"+separator;
            }
            else if(islc3)
            {
                data=data+"lcd_init("+"24"+");"+separator;
            }
            else if(islc4)
            {
                data=data+"lcd_init("+"40"+");"+separator;
            }
        }
        return data;

    }

    private String interuppt_init()
    {
        String data="";
        boolean isint0,isint1,isi2,isi3,isi4,isi1;

        isint0 = ((CheckBox) findViewById(R.id.checkBox49)).isChecked();
        isint1 = ((CheckBox) findViewById(R.id.checkBox50)).isChecked();
        isi1 = ((RadioButton) findViewById(R.id.I1)).isChecked();
        isi2 = ((RadioButton) findViewById(R.id.I2)).isChecked();
        isi3 = ((RadioButton) findViewById(R.id.I3)).isChecked();
        isi4 = ((RadioButton) findViewById(R.id.I4)).isChecked();
        if(isint0)
        {
            data=separator+data+"//External Interrupt 0 service Routine"+separator+separator+"interrupt [EXT_INT0] void ext_int0_isr(void)"+separator+"{"+separator+"//place your code here"+separator+separator+"}"+separator+separator;
        }
        if(isint1)
        {
            data=separator+data+"//External Interrupt 1 service Routine"+separator+separator+"interrupt [EXT_INT1] void ext_int1_isr(void)"+separator+"{"+separator+"//place your code here"+separator+separator+"}"+separator+separator;
        }
        return data;
    }

    private String interuppt_prog()
    {
        String data=separator+"//External Interrupt Initialization"+separator+separator;
        String data2="",data3="";
        boolean isint0,isint1,isi2,isi3,isi4,isi11,isi12,isi13,isi14,isi1;

        isint0 = ((CheckBox) findViewById(R.id.checkBox49)).isChecked();
        isint1 = ((CheckBox) findViewById(R.id.checkBox50)).isChecked();
        isi1 = ((RadioButton) findViewById(R.id.I1)).isChecked();
        isi2 = ((RadioButton) findViewById(R.id.I2)).isChecked();
        isi3 = ((RadioButton) findViewById(R.id.I3)).isChecked();
        isi4 = ((RadioButton) findViewById(R.id.I4)).isChecked();
        isi11 = ((RadioButton) findViewById(R.id.I11)).isChecked();
        isi12 = ((RadioButton) findViewById(R.id.I12)).isChecked();
        isi13 = ((RadioButton) findViewById(R.id.I13)).isChecked();
        isi14 = ((RadioButton) findViewById(R.id.I14)).isChecked();
        if(isint0 && isint1)
        {
            data=data+"GICR|=(1<<INT1)|(1<<INT0);"+separator+"GIFR=(1<<INTF1)|(1<<INTF0);"+separator;
        }
        else if(isint0 && !isint1)
        {
            data=data+"GICR|=(0<<INT1)|(1<<INT0);"+separator+"GIFR=(0<<INTF1)|(1<<INTF0);"+separator;
        }
        else if(!isint0 && isint1)
        {
            data=data+"GICR|=(1<<INT1)|(0<<INT0);"+separator+"GIFR=(1<<INTF1)|(0<<INTF0);"+separator;
        }
        if(isint0) {
            if (isi1) {
                data2 = data2 + "(0<<ISC01)|(0<<ISC00);";
            } else if (isi2) {
                data2 = data2 + "(0<<ISC01)|(1<<ISC00);";
            } else if (isi3) {
                data2 = data2 + "(1<<ISC01)|(0<<ISC00);";

            } else if (isi4) {
                data2 = data2 + "(1<<ISC01)|(1<<ISC00);";

            }
        }
        else
        {
            data2 = data2 + "(0<<ISC01)|(0<<ISC00);";
        }
        if(isint1) {
            if (isi11) {
                data3 = data3 + "(0<<ISC11)|(0<<ISC10)";
            } else if (isi12) {
                data3 = data3 + "(0<<ISC11)|(1<<ISC10)";
            } else if (isi13) {
                data3 = data3 + "(1<<ISC11)|(0<<ISC10)";

            } else if (isi14) {
                data3 = data3 + "(1<<ISC11)|(1<<ISC10)";

            }
        }
        else
        {
            data3 = data3 + "(0<<ISC11)|(0<<ISC10)";
        }
        data=data+"MCUCR="+data3+"|"+data2+separator;


        return data;
    }

    private String any_interrupt()
    {
        String data="";
        boolean isint0,isint1,isint2,isint3,isint4,isint5;

        isint0 = ((CheckBox) findViewById(R.id.checkBox49)).isChecked();
        isint1 = ((CheckBox) findViewById(R.id.checkBox50)).isChecked();
        isint2 = ((CheckBox) findViewById(R.id.checkBox56)).isChecked();
        isint3 = ((CheckBox) findViewById(R.id.checkBox57)).isChecked();
        isint4 = ((CheckBox) findViewById(R.id.checkBox58)).isChecked();

        if(isint0 | isint1 | isint2 | isint3 | isint4)
        {
            data=data+"#asm(\"sei\");"+separator;
        }
        return data;
    }

    private String usart_init()
    {
        String data="//USART INITILIZATION"+separator+separator;
        boolean x2,isusarttx,isusartrx,isu1,isu2,isu3,isu4,isu5,isu6,isuc1,isuc2,isuc3,isuc4;
        x2 = ((CheckBox) findViewById(R.id.checkBox55)).isChecked();
        isusarttx = ((CheckBox) findViewById(R.id.checkBox53)).isChecked();
        isusartrx = ((CheckBox) findViewById(R.id.checkBox54)).isChecked();
        isu1 = ((RadioButton) findViewById(R.id.U1)).isChecked();
        isu2 = ((RadioButton) findViewById(R.id.U2)).isChecked();
        isu3 = ((RadioButton) findViewById(R.id.U3)).isChecked();
        isu4 = ((RadioButton) findViewById(R.id.U4)).isChecked();
        isu5 = ((RadioButton) findViewById(R.id.U5)).isChecked();
        isu6 = ((RadioButton) findViewById(R.id.U6)).isChecked();
        isuc1 = ((RadioButton) findViewById(R.id.UC1)).isChecked();
        isuc2 = ((RadioButton) findViewById(R.id.UC2)).isChecked();
        isuc3 = ((RadioButton) findViewById(R.id.UC3)).isChecked();
        isuc4= ((RadioButton) findViewById(R.id.UC4)).isChecked();
        if(x2)
        {
            data=data+"UCSRA=(0<<RXC) | (0<<TXC) | (0<<UDRE) | (0<<FE) | (0<<DOR) | (0<<UPE) | (1<<U2X) | (0<<MPCM);"+separator;
        }
        else
        {
            data=data+"UCSRA=(0<<RXC) | (0<<TXC) | (0<<UDRE) | (0<<FE) | (0<<DOR) | (0<<UPE) | (0<<U2X) | (0<<MPCM);"+separator;
        }
        data=data+"UCSRB=(0<<RXCIE) | (0<<TXCIE) | (0<<UDRIE) | ";
        if(isusarttx)
        {
            data=data+"(1<<RXEN) | ";
        }
        else
        {
            data=data+"(0<<RXEN) | ";
        }
        if(isusartrx)
        {
            data=data+"(1<<TXEN) | ";
        }
        else
        {
            data=data+"(0<<TXEN) | ";
        }
        data=data+"(0<<UCSZ2) | (0<<RXB8) | (0<<TXB8);";

        if(isuc1)
        {
            data = data + separator + "UCSRC=(1<<URSEL) | (0<<UMSEL) | (0<<UPM1) | (0<<UPM0) | (0<<USBS) | (1<<UCSZ1) | (1<<UCSZ0) | (0<<UCPOL);" + separator;
        }
        else if(isuc2)
        {
            data = data + separator + "UCSRC=(1<<URSEL) | (0<<UMSEL) | (0<<UPM1) | (0<<UPM0) | (1<<USBS) | (1<<UCSZ1) | (1<<UCSZ0) | (0<<UCPOL);" + separator;
        }
        else if(isuc3)
        {
            data = data + separator + "UCSRC=(1<<URSEL) | (0<<UMSEL) | (1<<UPM1) | (0<<UPM0) | (0<<USBS) | (1<<UCSZ1) | (1<<UCSZ0) | (0<<UCPOL);" + separator;
        }
        else if(isuc4)
        {
            data = data + separator + "UCSRC=(1<<URSEL) | (0<<UMSEL) | (1<<UPM1) | (1<<UPM0) | (0<<USBS) | (1<<UCSZ1) | (1<<UCSZ0) | (0<<UCPOL);" + separator;
        }


        if(isu1)
        {
            if(x2)
            {
                data=data+"UBRRH=0x04;"+separator;
                data=data+"UBRRL=0x6F;"+separator;
            }
            else
            {
                data=data+"UBRRH=0x01;"+separator;
                data=data+"UBRRL=0xA0;"+separator;
            }
        }
        else if(isu2)
        {
            if(x2)
            {
                data=data+"UBRRH=0x00;"+separator;
                data=data+"UBRRL=0xCF;"+separator;
            }
            else
            {
                data=data+"UBRRH=0x00;"+separator;
                data=data+"UBRRL=0x67;"+separator;
            }
        }
        else if(isu3)
        {
            if(x2)
            {
                data=data+"UBRRH=0x00;"+separator;
                data=data+"UBRRL=0x67;"+separator;
            }
            else
            {
                data=data+"UBRRH=0x00;"+separator;
                data=data+"UBRRL=0x33;"+separator;
            }
        }
        else if(isu4)
        {
            if(x2)
            {
                data=data+"UBRRH=0x00;"+separator;
                data=data+"UBRRL=0x33;"+separator;
            }
            else
            {
                data=data+"UBRRH=0x00;"+separator;
                data=data+"UBRRL=0x19;"+separator;
            }
        }
        else if(isu5)
        {
            if(x2)
            {
                data=data+"UBRRH=0x00;"+separator;
                data=data+"UBRRL=0x19;"+separator;
            }
            else
            {
                data=data+"UBRRH=0x00;"+separator;
                data=data+"UBRRL=0x0C;"+separator;
            }
        }
        else if(isu6)
        {
            if(x2)
            {
                data=data+"UBRRH=0x00;"+separator;
                data=data+"UBRRL=0x0C;"+separator;
            }
            else
            {
                data=data+"UBRRH=0x00;"+separator;
                data=data+"UBRRL=0x06;"+separator;
            }
        }



        return data;

    }

    private String timer0_interrupt()
    {
        String data=separator;
        String timer_value;
        boolean ist0int,ist0stop;
        ist0int = ((CheckBox) findViewById(R.id.checkBox56)).isChecked();
        ist0stop = ((RadioButton) findViewById(R.id.t01)).isChecked();

        timer_value=timer0value.getText().toString();
        if(ist0int && !ist0stop)
        {
            data=data+"interrupt [TIM0_OVF] void timer0_ovf_isr(void)"+separator+"{"+separator+"TCNT0=0x"+timer_value+";"+separator+"}"+separator+separator;
        }
        return data;

    }

    private String timer_int_init()
    {
        String data1="//Timers/Counters Intrrrupt Initialization"+separator;
        String data2="",data3="",data4="",data5="";
        boolean ist0int,ist1int,ist2int,ist21int;
        ist0int = ((CheckBox) findViewById(R.id.checkBox56)).isChecked();
        ist1int = ((CheckBox) findViewById(R.id.checkBox57)).isChecked();
        ist2int = ((CheckBox) findViewById(R.id.checkBox58)).isChecked();
        ist21int = ((CheckBox) findViewById(R.id.checkBox59)).isChecked();
        if(ist0int)
        {
         data2=data2+"(1<<TOIE0)";
        }
        else
        {
            data2=data2+"(0<<TOIE0)";
        }
        if(ist1int)
        {
            data3=data3+"(1<<TOIE1)";
        }
        else
        {
            data3=data3+"(0<<TOIE1)";
        }
        if(ist2int)
        {
            data4=data4+"(1<<TOIE2)";
        }
        else
        {
            data4=data4+"(0<<TOIE2)";
        }
        if(ist21int)
        {
            data5=data5+"(1<<OCIE2)";
        }
        else
        {
            data5=data5+"(0<<OCIE2)";
        }
        data1=data1+"TIMSK="+data4+"|"+data5+"|"+"(0<<TICIE1) | (0<<OCIE1A) | (0<<OCIE1B)|"+data3+"|"+data2+";";

        return data1;
    }

    private String timer1_interrupt()
    {
        String data="";
        String timer_value;
        boolean ist0int,ist0stop;
        ist0int = ((CheckBox) findViewById(R.id.checkBox57)).isChecked();
        ist0stop = ((RadioButton) findViewById(R.id.t11)).isChecked();


        if(ist0int && !ist0stop)
        {
            data=separator+data+"interrupt [TIM1_OVF] void timer1_ovf_isr(void)"+separator+"{"+separator+"TCNT1=0x0000;"+separator+"}"+separator+separator;
        }
        return data;

    }

    private String timer2_interrupt()
    {
        String data="";
        String timer_value;
        boolean ist0int,ist0stop;
        ist0int = ((CheckBox) findViewById(R.id.checkBox58)).isChecked();
        ist0stop = ((RadioButton) findViewById(R.id.t21)).isChecked();


        if(ist0int && !ist0stop)
        {
            data=separator+data+"interrupt [TIM2_OVF] void timer2_ovf_isr(void)"+separator+"{"+separator+"TCNT2=0x00;"+separator+"}"+separator+separator;
        }
        return data;

    }

    private String timer2_compare_interrupt()
    {
        String data="";
        String timer_value;
        boolean ist0int,ist0stop;
        ist0int = ((CheckBox) findViewById(R.id.checkBox59)).isChecked();
        ist0stop = ((RadioButton) findViewById(R.id.t21)).isChecked();


        if(ist0int && !ist0stop)
        {
            data=separator+data+"interrupt [TIM2_COMP] void timer2_comp_isr(void)"+separator+"{"+separator+"//write your code here"+separator+"}"+separator+separator;
        }
        return data;

    }

    private String timer0_init()
    {
        String data="//Timer 0/Counter 0 Initialization"+separator+separator;
        String timer_value;
        boolean ist0stop,ist1000,ist15625,ist3906,ist977;
        ist0stop = ((RadioButton) findViewById(R.id.t01)).isChecked();
        ist1000 = ((RadioButton) findViewById(R.id.t02)).isChecked();
        ist15625 = ((RadioButton) findViewById(R.id.t03)).isChecked();
        ist3906 = ((RadioButton) findViewById(R.id.t04)).isChecked();
        ist977 = ((RadioButton) findViewById(R.id.t05)).isChecked();
        timer_value=timer0value.getText().toString();
        if(ist0stop)
        {
            data=data+"TCCR0=(0<<CS02) | (0<<CS01) | (0<<CS00);"+separator;
        }

        else if(ist1000)
        {
            data=data+"TCCR0=(0<<CS02) | (0<<CS01) | (1<<CS00);"+separator;
        }

        else if(ist15625)
        {
            data=data+"TCCR0=(0<<CS02) | (1<<CS01) | (1<<CS00);"+separator;
        }
        else if(ist3906)
        {
            data=data+"TCCR0=(1<<CS02) | (0<<CS01) | (0<<CS00);"+separator;
        }
        else if(ist977)
        {
            data=data+"TCCR0=(1<<CS02) | (0<<CS01) | (1<<CS00);"+separator;
        }
        data=data+"TCNT0=0x"+timer_value+";"+separator+separator;


        return data;

    }

    private String timer1_prog()
    {
        String data="//Timer 1 Initialization"+separator+separator;
        String data1="",data2="",data3="";
        boolean ist1stop,isnm,ispcpwm,isctc,isfpwm,ist11,isda,ista,isca,issa,isdb,istb,iscb,issb;
        ist1stop = ((RadioButton) findViewById(R.id.t11)).isChecked();
        ist11 = ((RadioButton) findViewById(R.id.t12)).isChecked();
        isnm = ((RadioButton) findViewById(R.id.tm11)).isChecked();
        ispcpwm = ((RadioButton) findViewById(R.id.tm12)).isChecked();
        isctc = ((RadioButton) findViewById(R.id.tm15)).isChecked();
        isfpwm = ((RadioButton) findViewById(R.id.tm16)).isChecked();
        isda = ((RadioButton) findViewById(R.id.ta11)).isChecked();
        ista = ((RadioButton) findViewById(R.id.ta12)).isChecked();
        isca = ((RadioButton) findViewById(R.id.ta13)).isChecked();
        issa = ((RadioButton) findViewById(R.id.ta14)).isChecked();
        isdb = ((RadioButton) findViewById(R.id.tb11)).isChecked();
        istb = ((RadioButton) findViewById(R.id.tb12)).isChecked();
        iscb = ((RadioButton) findViewById(R.id.tb13)).isChecked();
        issb = ((RadioButton) findViewById(R.id.tb14)).isChecked();


        if(ist1stop)
        {
            data=data+"TCCR1A=(0<<COM1A1) | (0<<COM1A0) | (0<<COM1B1) | (0<<COM1B0) | (0<<WGM11) | (1<<WGM10);"+separator+"TCCR1B=(0<<ICNC1) | (0<<ICES1) | (0<<WGM13) | (0<<WGM12) | (0<<CS12) | (0<CS11) | (1<<CS10);"+separator;
        }
        else if(ist11) {
            data = data + "TCCR1A=";
            if (isnm | isctc) {

                if (isda) {
                    data1 = "(0<<COM1A1) | (0<<COM1A0)";
                } else if (ista) {
                    data1 = "(0<<COM1A1) | (1<<COM1A0)";
                } else if (isca) {
                    data1 = "(1<<COM1A1) | (0<<COM1A0)";
                } else if (issa) {
                    data1 = "(1<<COM1A1) | (1<<COM1A0)";
                }
                if (isdb) {
                    data2 = "(0<<COM1B1) | (0<<COM1B0)";
                } else if (istb) {
                    data2 = "(0<<COM1B1) | (1<<COM1B0)";
                } else if (iscb) {
                    data2 = "(1<<COM1B1) | (0<<COM1B0)";
                } else if (issb) {
                    data2 = "(1<<COM1B1) | (1<<COM1B0)";
                }
                data = data + data1 + " | " + data2 + " | " + "(0<<WGM11) | (0<<WGM10);";
            }
            if (ispcpwm | isfpwm) {

                if (isda) {
                    data1 = "(0<<COM1A1) | (0<<COM1A0)";
                } else if (isca) {
                    data1 = "(1<<COM1A1) | (0<<COM1A0)";
                } else if (issa) {
                    data1 = "(1<<COM1A1) | (1<<COM1A0)";
                }
                if (isdb) {
                    data2 = "(0<<COM1B1) | (0<<COM1B0)";
                } else if (iscb) {
                    data2 = "(1<<COM1B1) | (0<<COM1B0)";
                } else if (issb) {
                    data2 = "(1<<COM1B1) | (1<<COM1B0)";
                }
                data = data + data1 + " | " + data2 + " | " + "(0<<WGM11) | (1<<WGM10);";
            }

            if(isnm | ispcpwm)
            {
                data=data+separator+"TCCR1B=(0<<ICNC1) | (0<<ICES1) | (0<<WGM13) | (0<<WGM12) | (1<<CS12) | (0<<CS11) | (1<<CS10);";
            }
            else if(isctc | isfpwm)
            {
                data=data+separator+"TCCR1B=(0<<ICNC1) | (0<<ICES1) | (0<<WGM13) | (1<<WGM12) | (1<<CS12) | (0<<CS11) | (1<<CS10);";
            }

            data=data+separator+"TCNT1H=0x00;"+separator+"TCNT1L=0x00;"+separator+"ICR1H=0x00;"+separator+"ICR1L=0x00;"+separator+"OCR1AH=0x00;"+separator+"OCR1AL=0x00;"+separator+"OCR1BH=0x00;"+separator+"OCR1BL=0x00;"+separator;

        }

        return data;

    }

    private String timer2_prog() {
        String data = "//Timer 2 Initialization" + separator + "ASSR=0<<AS2;" + separator, data2 = "";
        boolean ist2stop, ist21, isda, ista, isca, issa, isdm, istm, iscm, issm;
        ist2stop = ((RadioButton) findViewById(R.id.t21)).isChecked();
        ist21 = ((RadioButton) findViewById(R.id.t22)).isChecked();
        isda = ((RadioButton) findViewById(R.id.t021)).isChecked();
        ista = ((RadioButton) findViewById(R.id.t022)).isChecked();
        isca = ((RadioButton) findViewById(R.id.t023)).isChecked();
        issa = ((RadioButton) findViewById(R.id.t024)).isChecked();
        isdm = ((RadioButton) findViewById(R.id.t021)).isChecked();
        istm = ((RadioButton) findViewById(R.id.t022)).isChecked();
        iscm = ((RadioButton) findViewById(R.id.t023)).isChecked();
        issm = ((RadioButton) findViewById(R.id.t024)).isChecked();
        if (ist2stop) {
            data = data + "TCCR2=(1<<PWM2) | (0<<COM21) | (0<<COM20) | (1<<CT2) | (0<<CS22) | (1<<CS21) | (0<<CS20);" + separator + "TCNT2=0" + separator + "OXR2=0x00;";
        } else if (ist21) {

            if (isda) {
                data2 = "(0<<COM21) | (0<<COM20)";
            } else if (ista) {
                data2 = "(0<<COM21) | (1<<COM20)";
            } else if (isca) {
                data2 = "(1<<COM21) | (0<<COM20)";
            } else if (issa) {
                data2 = "(1<<COM21) | (1<<COM20)";
            }

            if (isdm) {
                data = data + "TCCR2=(0<<PWM2) | " + data2 + " | " + "(0<<CTC2) | (1<<CS22) | (1<<CS21) | (1<<CS20);";
            } else if (istm) {
                data = data + "TCCR2=(1<<PWM2) | " + data2 + " | " + "(0<<CTC2) | (1<<CS22) | (1<<CS21) | (1<<CS20);";
            } else if (iscm) {
                data = data + "TCCR2=(0<<PWM2) | " + data2 + " | " + "(1<<CTC2) | (1<<CS22) | (1<<CS21) | (1<<CS20);";
            } else if (issm) {
                data = data + "TCCR2=(1<<PWM2) | " + data2 + " | " + "(1<<CTC2) | (1<<CS22) | (1<<CS21) | (1<<CS20);";
            }
        }
        data = data + separator + "TCNT2=0x00;"+separator+ "OCR2=0x00;";
        return data;
    }

    private String end()
    {
        String data="while(1)"+separator+"{"+separator+"//place your code here"+separator+"}"+separator+"}";
        return data;
    }


}
